Repository HackathonOrc/hackathonTime1, pull requests merged in 2021-07, with the labels that each got.

#8 Solve #1 US01 - Cadastro
  Makefile
  app/package.json
  app/public/index.html
  app/src/App.tsx
  app/src/assets/abstract-user-flat-1.svg
  app/src/assets/home.svg
  app/src/assets/orcjump.png
  app/src/assets/orcsom2.png
  app/src/components/registerBox/index.tsx
  app/src/components/registerBox/style.css
  app/src/index.css
  app/src/pages/registerPage.tsx
  app/src/pages/registerPage/index.tsx
  app/src/pages/registerPage/style.css
  app/src/services/users.ts
  app/yarn.lock
  package.json
  server/package-lock.json
  server/package.json
  server/src/controllers/userController.ts
  server/yarn.lock
  yarn.lock
Labels: auth, backend, database, frontend

#9 Solve #3 - Feed
  app/src/App.tsx
  app/src/assets/fullHeart.svg
  app/src/assets/heart.svg
  app/src/assets/home.svg
  app/src/assets/log-out.svg
  app/src/components/posts/index.tsx
  app/src/components/posts/style.css
  app/src/pages/mainPage/mainPage.tsx
  app/src/pages/mainPage/style.css
  app/src/services/feed.tsx
  app/yarn.lock
  package.json
  server/src/controllers/feedController.ts
  server/src/models/feedSchema.ts
  server/src/routes/feedRoutes.ts
  server/src/routes/router.ts
  yarn.lock
Labels: backend, database, frontend

#10 Solve #2 login
  app/src/App.tsx
  app/src/components/posts/index.tsx
  app/src/pages/loginPage/loginPage.tsx
  app/src/pages/loginPage/style.css
  app/src/pages/registerPage/index.tsx
  app/src/services/users.ts
  server/package-lock.json
  server/package.json
  server/src/config/auth.secret.ts
  server/src/controllers/userController.ts
  server/src/models/userSchema.ts
  server/src/routes/feedRoutes.ts
  server/src/routes/userRoutes.ts
  server/src/services/middleware.ts
  server/yarn.lock
Labels: auth, backend, frontend

#13 Solve #3 Recuperação de Senha
  .gitignore
  app/src/App.tsx
  app/src/pages/loginPage/loginPage.tsx
  app/src/pages/passwordPage/passwordPage.tsx
  app/src/pages/passwordPage/style.css
  app/src/pages/recoveryPage/index.tsx
  app/src/pages/recoveryPage/style.css
  app/src/pages/registerPage/index.tsx
  app/src/services/users.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/passwordController.ts
  server/src/controllers/userController.ts
  server/src/routes/passwordRoutes.ts
  server/src/routes/router.ts
  server/src/routes/userRoutes.ts
  server/yarn.lock
Labels: auth, backend, database, frontend

#15 Solve #0X Logout
  app/src/pages/mainPage/mainPage.tsx
  app/src/pages/mainPage/style.css
  server/yarn.lock
Labels: auth, frontend

#19 Solve #7 Profile_Page
  app/public/index.html
  app/src/App.tsx
  app/src/assets/user_profile_temp.svg
  app/src/pages/mainPage/mainPage.tsx
  app/src/pages/mainPage/style.css
  app/src/pages/profilePage/profilePage.tsx
  app/src/pages/profilePage/style.css
  package.json
  yarn.lock
Labels: auth, frontend

#22 Solve #20 Dark Mode
  app/package-lock.json
  app/package.json
  app/src/components/posts/index.tsx
  app/src/components/posts/style.css
  app/src/components/posts/styled.ts
  app/src/components/themes/index.tsx
  app/src/pages/mainPage/mainPage.tsx
  app/src/pages/mainPage/style.css
  app/src/pages/mainPage/styled.ts
  app/src/pages/profilePage/profilePage.tsx
  app/src/pages/profilePage/style.css
  app/src/pages/profilePage/styled.ts
  app/yarn.lock
  package-lock.json
  yarn.lock
Labels: frontend
